routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('pages.welcomev2');
});

Route::get('search', 'SearchController@index');

Route::get('browse', function () {
    return view('pages.browse');
});

Route::get('about', function () {
    return view('pages.about');
});

Route::get('contact', function () {
    return view('pages.contact');
});

Route::get('download', function () {
    return view('pages.download');
});

Route::get('help', function () {
    return view('pages.help');
});

Route::get('database', function () {
    return view('pages.database');
});

Route::get('datasources', function () {
    return view('pages.datasources');
});

Route::get('glossary', function () {
    return view('pages.glossary');
});

Route::get('faqs', function () {
    return view('pages.faqs');
});
////////////////////////////////////////////////////////////
// DISPLAY
////////////////////////////////////////////////////////////

// Genes
Route::get('genes', 'GeneController@index')->name('genes.index');
Route::get('genes/{gene}', 'GeneController@show')->name('genes.show');
Route::get('datatables/genes', 'GeneController@datatablesGenes')->name('datatables.genes');

// Coexpressions
Route::get('coexpressions', 'CoexpressionController@index')->name('coexpressions.index');
Route::get('coexpressions/{coexpression}', 'CoexpressionController@show')->name('coexpressions.show');
Route::get('datatables/coexpressions', 'CoexpressionController@datatablesCoexpressions')->name('datatables.coexpressions');

// Compounds
Route::get('compounds', 'CompoundController@index')->name('compounds.index');
Route::get('compounds/{compound}', 'CompoundController@show')->name('compounds.show');
Route::get('datatables/compounds', 'CompoundController@datatablesCompounds')->name('datatables.compounds');

// Putatives
Route::get('putatives', 'PutativeController@index')->name('putatives.index');
Route::get('putatives/{putative}', 'PutativeController@show')->name('putatives.show');
Route::get('datatables/putatives', 'PutativeController@datatablesPutatives')->name('datatables.putatives');

// References
Route::get('references', 'ReferenceController@index')->name('references.index');
Route::get('references/{reference}', 'ReferenceController@show')->name('references.show');
Route::get('datatables/references', 'ReferenceController@datatablesReferences')->name('datatables.references');

// Results
Route::get('results', 'ResultController@index')->name('results.index');
Route::get('results/{result}', 'ResultController@show')->name('results.show');
Route::get('datatables/results', 'ResultController@datatablesResults')->name('datatables.results');

app/Reference.php
<?php

namespace App;
use App\Gene;
use Illuminate\Database\Eloquent\Model;

class Reference extends Model
{
  protected $table = 'references';
  protected $primaryKey = 'reference_id';

  public function genes()
  {
    return $this->belongsToMany(Gene::class, 'genes_references', 'reference_id', 'agi_id');
  }

    public function compounds()
  {
    return $this->belongsToMany(Compound::class, 'compounds_references', 'reference_id', 'compound_name');
  }

  
  // ACCESSORS
  public function getPubmedIdAttribute($value)
  {
    return !empty($value) ? $value : 'N/A';
  }

  public function getDoiAttribute($value)
  {
    return !empty($value) ? $value : 'N/A';
  }

  public function getPmcIdAttribute($value)
  {
    return !empty($value) ? $value : 'N/A';
  }

}

app/Http/Controllers/ReferenceController.php
<?php

namespace App\Http\Controllers;

use App\Reference;
use Illuminate\Http\Request;

class ReferenceController extends Controller
{
    /**
     * Display a listing of the resource..
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $references = Reference::query();

        if ($request->has('search_term')) {
            $term = $request->input('search_term');
            $references->where('reference_name', 'LIKE', '%'.$term.'%')
                    ->orWhere('year', 'LIKE', '%'.$term.'%')
                    ->orWhere('reference_title', 'LIKE', '%'.$term.'%')
                    ->orWhere('journal', 'LIKE', '%'.$term.'%')
                    ->orWhere('pubmed_id', 'LIKE', '%'.$term.'%');
        }

        $references = $references->get();

        return view('references.index', compact('references'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $reference = Reference::find($id);

        return view('references.show', compact('reference'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/references/index.blade.php
@extends('layout.mainlayout')

@section('style')
<style>
    div.DTTT_container {
        margin-left: 1em;
    }
    .dataTables_length {
        float: left !important;
    }
    .dataTables_wrapper .dt-buttons {
        float:right !important;
    }
    .dataTables_filter {
        float: right;
        margin-right: 1em;
    }
</style>
@endsection

@section('content')

<div class="album text-muted">
  <div class="container">
    <div class="row">
      <h3 class="jumbotron">Publications</h3>  
      <table id="references" class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Pubmed ID</th>
            <th>Year</th>
            <th>Authors</th>
            <th>Title</th>
            <th>Journal</th>
            <th>Description</th>
          </tr>
        </thead>
        @foreach ($references as $reference)
        <tr>
          <td>
            @if($reference->pubmed_id == 'N/A')
              <p>{{ $reference->pubmed_id }}</p>
            @else
              <p><a href="https://www.ncbi.nlm.nih.gov/pubmed/?term={{ $reference->pubmed_id }}" target="_blank">{{ $reference->pubmed_id }}</a></p>
            @endif      
          </td>
          <td>
            <p>{{ $reference->year }}</p>
          </td>
          <td>
            <p>{{ $reference->reference_name }}</p>
          </td>
          <td>
            <p>{{ $reference->reference_title }}</p>
          </td>
          <td>
            <p>{{ $reference->journal }}</p>
          </td>
          <td>
            <p><a href="{{ url('references/'.$reference->reference_id) }}" ><button class="btn btn-info">Link</button></a></p>
          </td>
        </tr>
        @endforeach
      </table>
    </div>
  </div>
</div>


@endsection


@section('scripts')
<script>
  $(function () {
    $('#references').DataTable({
      // dom: 'Brfltip',
      dom: '<lBf<t>ip>',
      buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5'
      ]
    });
  });
</script>

@endsection

resources/views/references/list.blade.php
<div class="row">
  <div class="col-md-12 px-0">
    @if(count($references))
      <table class="table table-striped">
      <thead>
        <tr>
          <th>Pubmed ID</th>
          <th>Authors</th>  
          <th>Year</th>
          <th>Title</th>
          <th>Journal</th>
          <th>Description</th>
        </tr>
      </thead>
        @foreach ($references as $reference)
        <tr>
          <td>
            <p><a href="https://www.ncbi.nlm.nih.gov/pubmed/?term={{ $reference->pubmed_id }}" target="_blank">{{ $reference->pubmed_id }}</a></p>
          </td>
          <td>
            <p>{{ $reference->reference_name }}</p>
          </td>
          <td>
            <p>{{ $reference->year }}</p>
          </td>
          <td>
            <p>{{ $reference->reference_title }}</p>
          </td>
          <td>
            <p>{{ $reference->journal }}</p>
          </td>
          <td>
            <p><a href="{{ url('references/'.$reference->reference_id) }}" ><button class="btn btn-info">Link</button></a></p>
          </td>
        </tr>
      @endforeach
      </table>
    @else {{-- if no references in search --}}
      <div class="text-center">
        <h3>No references found.</h3>
      </div>
    @endif
  </div>
</div>

resources/views/references/show.blade.php
@extends('layout.mainlayout')

@section('content')

<div class="album text-muted">
  <div class="container">
    <div class="row">
      <div class="m-b-md jumbotron">
        <h2>Publication Description</h2>
      </div>
      <table class="table profile-table">
        <tr>
          <td class="table-info col-md-2">Authors</td>
          <td class="table-detail col-md-10">{{ $reference->reference_name }}</td>
        </tr>
        <tr>
          <td class="table-info">Title</td>
          <td class="table-detail">{{ $reference->reference_title }}</td>
        </tr>
        <tr>
          <td class="table-info">Journal</td>
          <td class="table-detail">{{ $reference->journal }}</td>
        </tr>
        <tr>
          <td class="table-info">Volume</td>
          <td class="table-detail">{{ $reference->vol }}</td>
        </tr>
        <tr>
          <td class="table-info">DOI</td>
          @if($reference->doi == 'N/A')
          <td class="table-detail">{{ $reference->doi }}</td>
          @else
          <td class="table-detail"><a href="https://doi.org/{{ $reference->doi }}" target="_blank">{{ $reference->doi }}</td>
          @endif
        </tr>
        <tr>
          <td class="table-info">Pubmed ID</td>
          @if($reference->pubmed_id == 'N/A')
          <td class="table-detail">{{ $reference->pubmed_id}}</td>
          @else
          <td class="table-detail"><a href="https://www.ncbi.nlm.nih.gov/pubmed/?term={{ $reference->pubmed_id }}" target="_blank">{{ $reference->pubmed_id}}</a></td>
          @endif
        </tr>
        <tr>
          <td class="table-info">PMC ID</td>
          @if($reference->pmc_id == 'N/A')
          <td class="table-detail">{{ $reference->pmc_id}}</td>
          @else
          <td class="table-detail"><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/{{ $reference->pmc_id }}" target="_blank">{{ $reference->pmc_id}}</a></td>
          @endif
        </tr>
      </table>

        <ul class="nav nav-tabs">
          <li class="active">
            <a data-toggle="tab" href="#genes">
            Genes{{ count($reference->genes) ? ' ('.count($reference->genes).')' : '' }}
            </a>
          </li>
          <li><a data-toggle="tab" href="#compounds">
            Compounds{{ count($reference->compounds) ? ' ('.count($reference->compounds).')' : '' }}
          </a></li>
        </ul> 
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="genes">
            @include('genes.list', ['genes' => $reference->genes])
          </div>
          <div role="tabpanel" class="tab-pane" id="compounds">
            @include('compounds.list', ['compounds' => $reference->compounds])
          </div>
        </div> 

    </div>
  </div>
</div>
@endsection